package Biblioteca.GestionBibliotecaPackage;


/**
* Biblioteca/GestionBibliotecaPackage/ListaLibrosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Biblioteca.idl
* jueves 3 de abril de 2025 19H40' CEST
*/


// Define un tipo para secuencias de Libros
public final class ListaLibrosHolder implements org.omg.CORBA.portable.Streamable
{
  public Biblioteca.Libro value[] = null;

  public ListaLibrosHolder ()
  {
  }

  public ListaLibrosHolder (Biblioteca.Libro[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Biblioteca.GestionBibliotecaPackage.ListaLibrosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Biblioteca.GestionBibliotecaPackage.ListaLibrosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Biblioteca.GestionBibliotecaPackage.ListaLibrosHelper.type ();
  }

}
